---
title: Jordan Justice | Designer, developer, and thinker rooted in Toledo, Ohio.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jordan@jordanjustice.me
description: |
  Designer, developer, and thinker rooted in Toledo, Ohio.
baseurl: ''
url: http://jordanjustice.me
sass:
  style: :compressed
markdown: kramdown
