# Site settings
title: Jordan Justice | Designer, developer, and thinker rooted in Toledo, Ohio.
email: jordan@jordanjustice.me
description: > # this means to ignore newlines until "baseurl:"
  Designer, developer, and thinker rooted in Toledo, Ohio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jordanjustice.me" # the base hostname & protocol for your site

sass:
  style: :compressed

# Build settings
markdown: kramdown
