# Site settings
title: Jordan Justice
email: jordan@jordanjustice.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jordanjustice.me" # the base hostname & protocol for your site
twitter_username: jordi2108
github_username:  jordanjustice

# Build settings
markdown: kramdown
